### ISSUE TITLE
Incorrect errors in sample 2

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sybvals#11]
When I load sample 2 and investigate the list of errors carefully, I noted the following problems/inconsistencies:
- **Error 7**: glyph39 [*sis 1 (7) (7)*] is already in a compartment (nucleus), so why do we get this error?
- **Error 15**: *E3(San1)*->*AND* is mark some bluish color, whereas Error 15 is colored reddish?
- **Error 16** and **18**: both errors are associated with the same edge. In this case, shouldn't we color both errors and the edge to be the same? In this case, the edge is the same color with one of these errors but not the other one.

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz error 7 is solved by postprocess operation for process nodes before applying validation.
coloring issues are solved by giving same highlight colors to all errors related to same element, either node or edge.
