### ISSUE TITLE
Node sizes change after resolving errors

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/sybvals#15]
I think we lose the actual node sizes when we resolve errors. This can be seen in sample 2, just resolve errors, download SBGNML file and open it in Newt. All non-compound node sizes are 30 by 30.

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz @hasanbalci it works correct now. It occurs due to processing the process nodes before validation and solved by adding one if statement for resolve part.

**Comment by hasanbalci** [comment]
Node size issue looks solved, thanks! Another small issue I noticed: The below image is after resolving errors in Sample 2. Should we move the process outside into the compartment on the left? Actually if I download the SBGNML file and open it in Newt, I see that process node is inside the compartment. It seems that the file and image aren't consistent after we resolve the errors. ![polyq_proteins_interference (1)](https://github.com/iVis-at-Bilkent/sybvals/assets/22586369/3cb83a57-5e6d-40f6-b435-511acdcb8ffb)

**Comment by hasanbalci** [comment]
Also in same sample, I realized that there is an inconsistency in Error 2. There is a fix explanation but it seems unfixed. And label shows "(2)", but I cannot see any such label in the image.
<img width="472" alt="Screenshot 2024-06-30 at 16 13 13" src="https://github.com/iVis-at-Bilkent/sybvals/assets/22586369/6352628f-02de-4c50-a405-5cd64b5c35fc">

**Comment by YusufZiyaOzgul** [comment]
> Node size issue looks solved, thanks! Another small issue I noticed: The below image is after resolving errors in Sample 2. Should we move the process outside into the compartment on the left? Actually if I download the SBGNML file and open it in Newt, I see that process node is inside the compartment. It seems that the file and image aren't consistent after we resolve the errors. ![polyq_proteins_interference (1)](https://private-user-images.githubusercontent.com/22586369/344491421-3cb83a57-5e6d-40f6-b435-511acdcb8ffb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTk4NjcsIm5iZiI6MTcxOTgxOTU2NywicGF0aCI6Ii8yMjU4NjM2OS8zNDQ0OTE0MjEtM2NiODNhNTctNWU2ZC00MGY2LWI0MzUtNTExYWNkY2I4ZmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA3MzkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNGE4YjY0MTM2Y2M3YjFiODQxNWQ2NWY4MTIwZTY5NmUzOTkyYTIyMjJiODg4MDczM2NjYjA0MWM2MWEzOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Uymqtc9TZEzkOGSWowfr5jVjreAvwZ-C7nnuZGM_4B0)

@hasanbalci  I think is is related to Newt, not related to Sybvals. Try following steps,
first load sample 2 do validation and resolve, then download the sbgn file.
Then upload it to both sybvals and newt, corresponding maps are different but.
Content of the sbgn file is changed in newt. There is no compartment ref related to process node you mentioned, but it in newt, it is compartment referenced.

**Comment by hasanbalci** [comment]
@YusufZiyaOzgul Newt also applies a postprocessing for process nodes while loading the file, so it may not be a good place to test this issue. But if you check the content of the file downloaded from Sybvals after error fixing, you can see that there are 2 processes, 1 uncertain process and 2 association nodes without compartment references. You can also see that when you upload it to Syblars which doesn't apply any postprocessing on process nodes. 
![polyq_proteins_interference (3)](https://github.com/iVis-at-Bilkent/sybvals/assets/22586369/bc4663e0-edff-4172-a3ec-3968d1d8ef0d)

**Comment by hasanbalci** [comment]
This seems resolved.
