### ISSUE TITLE
Support for new error types  

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/sybvals#16]
Support below error codes:
- [x] 1. pd10001: ID needs to be unique
- [x] 2. pd10002: An arc source/target should be a glyph defined in the diagram
- [x] 3. pd10110: Modulation arc must have target reference to PN classes
- [x] 4. pd10127: Arc with class equivalence arc must have source reference to glyph of EPN classes
- [x] 5. pd10128: Arc with class equivalence arc must have target reference to glyph of classes 'tag', 'submap' or 'terminal'
- [x] 6. pd10141: All process nodes should have at least one input and at least one ouput

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz @hasanbalci for item 3, modulation arc target is connected to one of the nearby PN's as a resolution, for item 4, equivalence arc source is connected to one of the nearby EPN's as a resolution, for item 5, equivalence arc target is connected to one of the nearby 'tag', 'submap' or 'terminal'. for item 6, process is connected to one of the nearby EPN's as an input with class consumption arc if input is missing, process is connected to one of the nearby EPN's as output with class production arc if output is missing.

**Comment by hasanbalci** [comment]
@YusufZiyaOzgul For item 6, please see #27.

**Comment by hasanbalci** [comment]
For item 3, 4, 5 and 6, fix explanations should be corrected. Currently, it always says "Fix of another error resolved this error." when these error types are resolved, even though we select one of the suggested choices.

**Comment by YusufZiyaOzgul** [comment]
> For item 3, 4, 5 and 6, fix explanations should be corrected. Currently, it always says "Fix of another error resolved this error." when these error types are resolved, even though we select one of the suggested choices. But the fixes work correctly for these items except item 6. So we should fix the fix problem in item 6 and explanations for items 3, 4, 5 and 6.

@hasanbalci @ugurdogrusoz fix explanations are added for item 3,4,5,6 and now it works correct. the resolve for item 6 works correct now.

**Comment by hasanbalci** [comment]
The fix explanations for item 3, 4, 5, 6 and resolve for item 6 are now correctly working. But for pd10001 and pd10002, cannot we add errors like in the other cases? When these errors exist, we can still load the maps and apply validation, but only the node with non-unique id or the arc without source or target is not drawn. So I think if these errors exist we can continue to validation as before, but we can add these errors to the error list shown on the left panel.

**Comment by ugurdogrusoz** [comment]
> The fix explanations for item 3, 4, 5, 6 and resolve for item 6 are now correctly working. But for pd10001 and pd10002, cannot we add errors like in the other cases? When these errors exist, we can still load the maps and apply validation, but only the node with non-unique id or the arc without source or target is not drawn. So I think if these errors exist we can continue to validation as before, but we can add these errors to the error list shown on the left panel. @ugurdogrusoz What do you think?

We can do it like @hasanbalci suggests if not very difficult.

**Comment by ugurdogrusoz** [comment]
Let's try solving items 1 & 2 as discussed over Skype.

**Comment by YusufZiyaOzgul** [comment]
> Let's try solving items 1 & 2 as discussed over Skype.

@ugurdogrusoz @hasanbalci these items are solved as discussed.

**Comment by hasanbalci** [comment]
@YusufZiyaOzgul For pattern pd10141, please make sure that we only suggest nodes from EPN class.

**Comment by hasanbalci** [comment]
For pattern pd10001, can we print the error only one time for each id that is not unique. Currently if there are two nodes with the same id, we see the error twice.

**Comment by hasanbalci** [comment]
@YusufZiyaOzgul They look good, thanks!
