### ISSUE TITLE
Clean code and dependencies

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/sybvals#18]
After major code-related issues are solved, let's clean the code, remove commented parts and console.log statements, remove unnecessary dependencies from package.json etc. so that we leave a decent coding environment for the maintainers.

**Comment by YusufZiyaOzgul** [comment]
@hasanbalci @ugurdogrusoz cleanup is done.

**Comment by hasanbalci** [comment]
- Are we using the following files:
  - syblars_error.log file in root folder
  - main.menu.js in src folder
  - stylesheetNewt.js in src folder
- There are some variables named as "syblars" in public/js/main.menu.js file. Can we change them to "sybvals"?
- I also see some commented lines especially in src/index.js and public/js/main.menu.js (like [here](https://github.com/iVis-at-Bilkent/sybvals/blob/fb48f1ea06ba36ec5a87361b9b12a2f6e9f18613/src/index.js#L1874) and [here](https://github.com/iVis-at-Bilkent/sybvals/blob/fb48f1ea06ba36ec5a87361b9b12a2f6e9f18613/public/js/main.menu.js#L794))) and multiple consecutive empty lines (like [here](https://github.com/iVis-at-Bilkent/sybvals/blob/fb48f1ea06ba36ec5a87361b9b12a2f6e9f18613/public/js/main.menu.js#L382)). Can you please remove them?

**Comment by YusufZiyaOzgul** [comment]
> * Are we using the following files:
>       
>       * syblars_error.log file in root folder
>       * main.menu.js in src folder
>       * stylesheetNewt.js in src folder
> 
>     * There are some variables named as "syblars" in public/js/main.menu.js file. Can we change them to "sybvals"?
> 
>     * I also see some commented lines especially in src/index.js and public/js/main.menu.js (like [here](https://github.com/iVis-at-Bilkent/sybvals/blob/fb48f1ea06ba36ec5a87361b9b12a2f6e9f18613/src/index.js#L1874) and [here](https://github.com/iVis-at-Bilkent/sybvals/blob/fb48f1ea06ba36ec5a87361b9b12a2f6e9f18613/public/js/main.menu.js#L794))) and multiple consecutive empty lines (like [here](https://github.com/iVis-at-Bilkent/sybvals/blob/fb48f1ea06ba36ec5a87361b9b12a2f6e9f18613/public/js/main.menu.js#L382)). Can you please remove them?
> 
>     * I also see sbgnml-to-cytoscape as a dependency in package.json. I guess we're not using it, are we?

@hasanbalci I consider it again and remove unnecessary parts mentioned above.
