### ISSUE TITLE
Resolve inconsistency

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sybvals#19]
With sample 2, the list shows an error where the corresponding edge is not highlighted:

<img width="634" alt="Screenshot 2024-07-10 at 18 40 13" src="https://github.com/iVis-at-Bilkent/sybvals/assets/3874988/cb7ed0f2-5625-43f4-954b-412868510d55">

**Comment by ugurdogrusoz** [comment]
Looks like before resolving these, we have an issue with the error itself. Here edges connecting to the AND node seem to be correct edges yet we signal errors (same behavior with Newt). So we should first fix this before we see if there is still this inconsistency.

Newt does validation [here](https://github.com/iVis-at-Bilkent/newt/blob/master/app/js/inspector-utilities.js). I guess sybvals has a copy of this code in its own repo.

**Comment by ugurdogrusoz** [comment]
Further investigation yields that the issue with the map is not that the target of logic arc is not a logical operator but it's not a **port** of a logical operator (that's what proper SBGN asks for).

Short-term solution: ignore this error report if the target is indeed a logical operator
Long-term solution: create ports for the logical operator and connect the logic arc to the proper port (instead of directly connecting it to the logical operator)

Obviously, the same needs to be done for symmetric errors.

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz fixed by applying short term solution. Checked each error and if target is logical operator, error is ignored. Similar error type is pd10142 and same logic is also applied for pd10142

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz @hasanbalci same logic is applied for pd10109, pd10111, pd10124, pd 10126.

**Comment by ugurdogrusoz** [comment]
Since this turned out to be related to not having ports on logical operators, I am creating a separate issue specifically on this and closing this one.
