### ISSUE TITLE
Update demo samples to contain a variety of validation issues

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sybvals#21]

**Comment by hasanbalci** [comment]
@ugurdogrusoz I updated samples, can you please check them?

**Comment by ugurdogrusoz** [comment]
- Load Sample 1
- Validate
- Resolve Errors
- Resolve Errors again and we get the following error:
<img width="359" alt="Screenshot 2024-08-17 at 00 07 27" src="https://github.com/user-attachments/assets/16f5ca0e-8935-4de3-81af-8d6e46e9463b">

**Comment by ugurdogrusoz** [comment]
@hasanbalci Can we add 1 more sample (Sample 0?) which has a few different errors all of which get resolved in a first attempt?

**Comment by hasanbalci** [comment]
I added one more sample.

**Comment by YusufZiyaOzgul** [comment]
> * Load Sample 1
> 
>     * Validate
> 
>     * Resolve Errors
> 
>     * Resolve Errors again and we get the following error:
> 
> 
> <img alt="Screenshot 2024-08-17 at 00 07 27" width="359" src="https://private-user-images.githubusercontent.com/3874988/358726489-16f5ca0e-8935-4de3-81af-8d6e46e9463b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNTg5ODYsIm5iZiI6MTcyNDE1ODY4NiwicGF0aCI6Ii8zODc0OTg4LzM1ODcyNjQ4OS0xNmY1Y2EwZS04OTM1LTRkZTMtODFhZi04ZDZlNDZlOTQ2M2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjBUMTI1ODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDkxMTY3OWM3Zjc2NDFjYzRiMzRlMmQyY2FjYzJhNDAyN2JlNDRiMGRjYzMzZTNjZTNhZDBmODE2YzYzZjI0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jTNavFHXBOguuRZD4-PIgt8HhvMKMpNtczWtZayGiRU">

@ugurdogrusoz I can not reproduce this.
