### ISSUE TITLE
Parallel usage issues

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sybvals#23]
Currently, if two people use the demo simultaneously with different maps, the result from one user might be shown to the other.

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz the reason of this issue if global variable usage. instead of using global variables, usage of req.locals or res.locals variables of requests supports paralel usage.

**Comment by ugurdogrusoz** [comment]
Well done @YusufZiyaOzgul This looks resolved to me
@hasanbalci Please test as well (let me know if you'd like to do it together)

**Comment by hasanbalci** [comment]
Looks good!
