### ISSUE TITLE
Error on resolve

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sybvals#26]
We'll be able to validate the below map without issues but trying to resolve the errors will yield an error:
<img width="356" alt="Screenshot 2024-07-16 at 15 45 24" src="https://github.com/user-attachments/assets/34d94f18-6042-457a-b5ee-4736c1262c32">

[new_file.sbgn.txt](https://github.com/user-attachments/files/16255894/new_file.sbgn.txt)

**Comment by hasanbalci** [comment]
Same for this file: 
[new_file_4.nwt.txt](https://github.com/user-attachments/files/16257476/new_file_4.nwt.txt)
We can then try to catch any errors so it can continue working.

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz @hasanbalci the reason of problem is undefined types, like array[0].property for empty array. Fixed by necessary if statements.
