### ISSUE TITLE
Improved resolution of errors with help from user

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sybvals#29]
Let's give users a chance to make choice about fixes as follows:
**In the API**:
- Add a parameter `calcFixChoices` to validation to specify whether or not they would like to see a potential list of fixes for each error when applicable. If this parameter is true, then the service should return a list of potential fixes to the user along with other information.
- Add an **optional** parameter `choicesForFixes` for resolving errors that contains the choices of the user for the fix of each error (may be 0 means do not fix; 1 means the first - default - choice, etc.). The resolve operation will take these into account and fix the error by the provided choice. In case a previous fix breaks the current fix, we should skip it.

**In the demo**:
- List all choices, if applicable, for the fix of an error in the Error list (initially collapsed to save space). The first (default) fix should be selected by default. The user could change this to other possibilities.
- When resolve is applied, the choices will be passed to the associated API.
- After a resolve operation, any remaining errors should be listed with potential fixes and the Resolve Errors button should be enabled (disable this button only when there are no errors or all errors have been fixed).

**Comment by ugurdogrusoz** [comment]
Items to do/improve:
- [ ] 1. Update the README to reflect usage/API changes
- [ ] 2. Rearrange the Settings (bring related items closer so they are separated from the rest in the same row) and add the "Show Resolution Alternatives" checkbox (`true` by default)
<img width="784" alt="Screenshot 2024-07-25 at 16 09 10" src="https://github.com/user-attachments/assets/4414291a-b4c8-4512-b844-c22b667a76ad">

- [ ] 3. Use class name (e.g. "Omitted Process") as a label for a node when it has no label
 
- [ ] 4. Rearrange error list items to be compact:
<img width="475" alt="Screenshot 2024-07-25 at 16 21 45" src="https://github.com/user-attachments/assets/f39143e5-d6dd-4d61-8c02-1a09cd175411">

- [ ] 5. Improve resolution alternatives GUI:
<img width="596" alt="Screenshot 2024-07-25 at 16 30 05" src="https://github.com/user-attachments/assets/634a4611-89a6-4f6c-b288-09537599f5d2">

**Comment by ugurdogrusoz** [comment]
for 2: separating spaces 1, 2, 3, and 4 in the image below should be equal and these option groups should be spread out as shown in 5 (right aligned as marked)
<img width="806" alt="Screenshot 2024-07-31 at 17 08 43" src="https://github.com/user-attachments/assets/46b70f91-eace-4849-87c4-409584d8f73c">

for 5: here are additional improvements:
<img width="696" alt="Screenshot 2024-07-31 at 17 16 57" src="https://github.com/user-attachments/assets/3c1ab512-2f2c-4f3f-b2cf-0f53bd0d5ae9">

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz @hasanbalci for item 7, scrollbar is made hidden, for item 9 image format is selected correctly after resolve operation, for item 10 text on error box is not updated before new sbgn file is uploaded, for seperating spaces 65px margin is given for all 1,2,3 and 4. Unnecessary spaces in accordion is removed. I check font famiy of "Resolution Alternatives", it looks same with others, font-family :Lato.

**Comment by ugurdogrusoz** [comment]
item 8 is not addressed, the rest seem to be resolved.

**Comment by hasanbalci** [comment]
Added item 11.

**Comment by ugurdogrusoz** [comment]
With item 5, we're not using the same arrows as dropdown boxes for consistency

**Comment by hasanbalci** [comment]
@YusufZiyaOzgul Is it possible for an error to persist in its first color during its lifetime?

**Comment by ugurdogrusoz** [comment]
> @YusufZiyaOzgul Is it possible for an error to persist its first assigned color until it is resolved?

Added this as item 12

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz @hasanbalci item 8 is fixed by adding margin and item 5 is fixed by using "icon small angle down" class of semantic ui.

**Comment by ugurdogrusoz** [comment]
Remaining problems with item 5:
- expanded and collapsed arrows are the same (they used to/should be different facing down and to the right; now both are facing down).
- now the arrows for the combo boxes are different; we were trying to make them all the same/consistent.
<img width="545" alt="Screenshot 2024-08-12 at 23 30 52" src="https://github.com/user-attachments/assets/870a5a2b-1ef5-4afd-ab46-7a4eab5badfd">
