### ISSUE TITLE
Error on validation

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sybvals#3]
Sample 3 will not validate properly (never returns)

**Comment by ugurdogrusoz** [comment]
Looks like this is related to the fact that Cytoscape SBGN stylesheet does not handle submaps and this particular map has a submap. Let's just replace this sample with something else and keep this issue open.

**Comment by YusufZiyaOzgul** [comment]
Drosophila cell cycle is added.
