### ISSUE TITLE
Popped image will not resize to be bigger

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sybvals#30]
When I pop a constructed image and then resize its container window to be bigger, I expect the image to get resized/bigger for easier readability but it doesn't! I think this used to work fine in the past.

https://github.com/user-attachments/assets/3dd95bb0-deec-4b98-a1a4-b7128334bf19

**Comment by YusufZiyaOzgul** [comment]
@hasanbalci @ugurdogrusoz it is fixed now.

**Comment by hasanbalci** [comment]
Looks good.
