### ISSUE TITLE
Proper handling of internal errors

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sybvals#34]
Currently, when an error is encountered, sometimes the server will crash not gracefully handling the problem so, let's rectify these situations. A generic error that pops up saying "Invalid map or unsupported content!" would be good.

Specifically for example:

- We do not support submaps in SBGN (mainly due to SBGN stylesheet not supporting them).
- File content might be faulty (syntax error for instance),

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz @hasanbalci now it gives an generic error message, server does not crash.

**Comment by hasanbalci** [comment]
Looks good to me.

**Comment by ugurdogrusoz** [comment]
Can we please add a title to the popup (similar to the ABOUT box) using the same style and the title "ERROR"?

**Comment by YusufZiyaOzgul** [comment]
> Can we please add a title to the popup (similar to the ABOUT box) using the same style and the title "ERROR"?

@ugurdogrusoz it is added now.
