### ISSUE TITLE
Choice to ignore error when resolving errors

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sybvals#35]
We should give the user an option to ignore/skip an error. On the API side, if the user does not provide a value for `selectedOption`, we should ignore that error (no fix). If a value is provided, then apply it.
In the demo application, we should give the user an additional option "none" (as a first option; we should still bring the default fix as selected though). If none is selected by the user, we should ignore the error.

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz @hasanbalci now, none option is added to demo and is shown as at the top. If there is no selectedOption, error is ignored.

**Comment by ugurdogrusoz** [comment]
I checked the sample app; the option "None" is there. But there are some other problems:
- [ ] 1. On Windows, the combo box width is not enough to hold some sample names. Let's slightly increase the width of this combo box:
<img width="285" alt="Screenshot 2024-08-19 at 20 19 04" src="https://github.com/user-attachments/assets/83153981-177b-4259-b2d4-0a3071e54da8">

- [ ] 2. When we cannot solve an error, we should not list any resolution alternatives (that only contain "None" as an option). I think this results in some other inconsistencies.

- [ ] 3. When multiple processes are listed as resolution alterative, we just list "process, process, process, ..." which is ambiguous. For processes, let's use "process with input(s)/output(s) xyx" where "xyz" is a list of all input and output EPN labels. If "xyz" is empty, we should just display "process" as before.

- [ ] 4. Similar to processes, with logic gates, let's use "{and,or,not} with input(s)/output(s) xyz", where "xyz" is a list of input and/or output EPN labels. Notice there that some of the inputs/outputs might be non-EPNs (other logic gates or processes); in that case, they are not listed. If "xyz" is empty, we should just display "{and,or,not}" as before.

- [ ] 5. When you resolve errors and re-list remaining errors we get "Resolution Alternative" (singular) rather than "Resolution Alternatives". This is also worrying since it points to not re-using associated code.

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz now changes done for all items listed above.
