### ISSUE TITLE
Missing coordinates for empty set nodes in resulting SBGN file

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/sybvals#38]
In sample 2, when we resolve errors and separate empty set (source and sink) nodes and then download the resulting SBGNML file, empty set nodes don't have coordinates. If we load it to Newt, we cannot see those nodes.

**Comment by YusufZiyaOzgul** [comment]
@hasanbalci @ugurdogrusoz now, source and sink nodes have position. This bug occurs as they get undefined values for their x and y coordinates. Now, they have true values.
