### ISSUE TITLE
Misc issues 2

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/sybvals#5]
- [x] 1. With Sample 2, some errors that have been fixed do not have an **explanation** (see 17 & 18 below)
<img width="502" alt="image" src="https://github.com/iVis-at-Bilkent/sbgn-validation-service/assets/3874988/06f7bbde-2c49-419d-9625-59f97efdd8b6">

- [x] 2. Again with Sample 2, when you resolve errors, even though four of them (1, 2, 17, and 18) are left, the error count is 1 in the title.

- [x] 3. Fix explanation messages should be grammatically correct (Fixed by **moving** glyph18 inside glyph0):
<img width="487" alt="image" src="https://github.com/iVis-at-Bilkent/sbgn-validation-service/assets/3874988/623acdfa-8823-4231-939c-0269dd011a7c">

- [x] 4. When input and output EPNs (e.g. macromolecules) of a process are moved inside a compartment, and the associated process stays outside, we have poor layouts. Hence, let's have a post-processing phase in resolving errors, where we check to see if any EPN was moved inside a compartment, and if so check whether the associated process is outside any compartments. If so, also check if all inputs and outputs of the process are in the same compartment. In such cases, we should move the process to the same compartment as well. This should be done **after all fixes** are applied for efficiency reasons and **before** layout.

- [x] 5. When an error is resolved, the corresponding item's borders in the error list should no longer be color-coded but be gray.

- [x] 6. When the given file is valid, we should 1) display "(none)" instead of "(0)", 2) get rid of the gray box aligned with "Map is valid!" message, 3) apply orphan (no compartment) logic for processes even when the map is valid before layout.

- [x] 7. The popup image (when you click on the image on the right) is not relocatable. Often times, users will want to move it to the right and see the error list on the left while looking at this image.

**Comment by ugurdogrusoz** [comment]
1. Looks good. Let's not repeat the name of the glyph/arch in the explanation though since it's already provided as the **role**.
![Untitled](https://github.com/iVis-at-Bilkent/sbgn-validation-service/assets/3874988/990d71e6-a1f9-47ad-ad69-9b314209e4cd)

**Comment by ugurdogrusoz** [comment]
1. "Fix of another error triggered fix of this error." -> "Fix of another error resolved this error."
6. get rid of the gray box aligned with "Map is valid!" message
<img width="525" alt="Screenshot 2024-05-19 at 15 00 27" src="https://github.com/iVis-at-Bilkent/sbgn-validation-service/assets/3874988/0ade2005-365e-40e0-a187-0cb3d002188a">

**Comment by hasanbalci** [comment]
@YusufZiyaOzgul Let`s place the Auto checkbox to the right of Width and Height options as in the Transparent checkbox. In addition, don`t forget to add this option to the control of "Reset to default" button.

**Comment by ugurdogrusoz** [comment]
Some remaining minor issues:
- Reset to default ignore the "Auto" checkbox in resolution
- Handle in popped up image should have an orange background and the close icon should have the same color as the other icons (dark gray)
- Text on the handle in popped up image should have some padding around it

**Comment by hasanbalci** [comment]
I think we need to use four-headed arrow while only mouse cursor is on the top bar of the draggable image window. Because we allow user to drag the window only from top bar, and it doesn't make sense to show it while the cursor is over the image.

**Comment by ugurdogrusoz** [comment]
Another minor problem here is an incorrect tooltip for the Close (X) button:
<img width="257" alt="Screenshot 2024-06-14 at 14 49 09" src="https://github.com/iVis-at-Bilkent/sybvals/assets/3874988/95bf777c-ed66-4daf-8c11-245bd20048b1">

**Comment by ugurdogrusoz** [comment]
@YusufZiyaOzgul what's the status of this issue? If done you should unassign yourself.

**Comment by ugurdogrusoz** [comment]
> I think we need to use four-headed arrow while only mouse cursor is on the top bar of the draggable image window. Because we allow user to drag the window only from top bar, and it doesn't make sense to show it while the cursor is over the image. As an alternative, we should allow user to drag the window while the cursor is over the popup window.

My suggestion is to have the plus icon on the top bar where dragging is possible (current behavior) and have the pointing hand icon on the draggable image window **and** the close icon. When the user clicks on the draggable image window as well as the close icon, we could dock the window back to the original place.

**Comment by YusufZiyaOzgul** [comment]
> I think we need to use four-headed arrow while only mouse cursor is on the top bar of the draggable image window. Because we allow user to drag the window only from top bar, and it doesn't make sense to show it while the cursor is over the image. As an alternative, we should allow user to drag the window while the cursor is over the popup window.

four headed arrow is only available in top bar of draggable image window, in image area there is a pointing hand icon.
