### ISSUE TITLE
Errors in deployment

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/sybvals#8]
- [x] When I click on "Errors" download button when no file is uploaded, it throws an error in the console. It doesn't prevent the program from running, but let's fix it anyway.
- [x] After I resolve errors in Sample 1 & 2, download the SBGNML files and then try to open them in Newt, it throws an error in the console and the maps cannot be loaded.
- [x] When I tried to validate "Insulin-like growth factor (IGF) signaling" map from Newt samples, it gives error "Error detail: SyntaxError: Unexpected token '<', "". 
- [x] When I tried to validate "Drosophila cell cycle" map from Newt samples, even though Newt shows 3 errors, sybvals shows 6 errors (I think it also adds the reverse version of each error) and doesn't highlight the errors. Additionally, when tried to resolve errors, it returns an error dialog.
- [x]  [vitamins_b6_activation_to_pyridoxal_phosphate.sbgn.txt](https://github.com/user-attachments/files/15841893/vitamins_b6_activation_to_pyridoxal_phosphate.sbgn.txt) When we validate this file, service finds 25 errors but error numbers start from 15 and go to 39. In addition, resolving errors give error. 
- [x] For the examples given in README, I used [test.sbgn.txt](https://github.com/user-attachments/files/16006814/test.sbgn.txt). it is a small file with only 3 nodes and two edges. When I test it, validation works correctly, but error resolving gives error.

**Comment by YusufZiyaOzgul** [comment]
Now, sample SBGNML files( after error resolving) successfully opened in Newt. I tried to click "Errors" download button when there is no file uploaded and I didn't get any error. Third error is related to #3. Reason of this error is "submap" is not handled in stylesheet.

**Comment by hasanbalci** [comment]
In item 1, I still see the mentioned error.
I also added a new item (item 4).

**Comment by hasanbalci** [comment]
I see that only item 1 is resolved. I ignored item 3, but there is no change in item 4.

**Comment by hasanbalci** [comment]
For item 4, we now show 3 errors and highlight them, it is ok. But when I try to resolve errors in 
[drosophila_cell_cycle.nwt.txt](https://github.com/user-attachments/files/15837391/drosophila_cell_cycle.nwt.txt) it works but if I try [drosophila_cell_cycle.sbgn.txt](https://github.com/user-attachments/files/15837405/drosophila_cell_cycle.sbgn.txt) it gives error. I generated the first file with save in Newt and the second one by exporting as SBGN-ML Plain. Please remove .txt from the extensions to test the files.

**Comment by hasanbalci** [comment]
Added a new item (item 5).

**Comment by YusufZiyaOzgul** [comment]
@hasanbalci item5( vitamin b6) is working now. It is related to listing pd10102 errors.

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz item 6 ( test.sbgn) is now working. Reason of error is that test.sbgn does not include mapProperties, so there is undefined errors in code, it is fixed by adding if else statement.

**Comment by YusufZiyaOzgul** [comment]
> For item 4, we now show 3 errors and highlight them, it is ok. But when I try to resolve errors in [drosophila_cell_cycle.nwt.txt](https://github.com/user-attachments/files/15837391/drosophila_cell_cycle.nwt.txt) it works but if I try [drosophila_cell_cycle.sbgn.txt](https://github.com/user-attachments/files/15837405/drosophila_cell_cycle.sbgn.txt) it gives error. I generated the first file with save in Newt and the second one by exporting as SBGN-ML Plain. Please remove .txt from the extensions to test the files.

it is working for both .sbgn and .nwt files now. @hasanbalci

**Comment by hasanbalci** [comment]
@YusufZiyaOzgul Thanks, droshophila example works now. However, after we resolve its errors, if we download the SBGN file and try to validate again, it finds a new error with an element unrelated to the previous ones. This doesn't happen in Newt.
